# Generated by Django 5.0.4 on 2024-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/')),
                ('description', models.CharField(max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('borrowed_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('issuedby', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('returndate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
