# Generated by Django 5.0.4 on 2024-09-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrowed_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
